apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: autoscaler
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30007
